# A sample Gemfile
source "https://rubygems.org"

ruby '2.5.3'

gem "rake"
gem "sinatra"
gem "minitest"
gem "rack-test", require: "rack/test"
gem "rack-parser", require: "rack/parser"
gem "nori"
gem "nokogiri"