//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ServiceModel;

namespace Customers
{
    [ServiceContract(Namespace = "http://www.galasoft.ch", ConfigurationName = "CustomerService")]
    public interface ICustomerService
    {

        [OperationContract(Action = "http://www.galasoft.ch/CustomerService/GetCustomers", ReplyAction = "http://www.galasoft.ch/CustomerService/GetCustomersResponse")]
        Customers.Customer[] GetCustomers(string lastName);

        [OperationContract(Action = "http://www.galasoft.ch/CustomerService/GetCustomerByAccountNumber", ReplyAction = "http://www.galasoft.ch/CustomerService/GetCustomerByAccountNumberResponse")]
        Customers.Customer GetCustomerByAccountNumber(int accountNumber);

        [OperationContract(Action = "http://www.galasoft.ch/CustomerService/GetAllCustomers", ReplyAction = "http://www.galasoft.ch/CustomerService/GetAllCustomersResponse")]
        Customers.Customer[] GetAllCustomers();

        [OperationContract(Action = "http://www.galasoft.ch/CustomerService/SaveCustomer", ReplyAction = "http://www.galasoft.ch/CustomerService/SaveCustomerResponse")]
        bool SaveCustomer(Customers.Customer editedCustomer);

        [OperationContract(Action = "http://www.galasoft.ch/CustomerService/SaveCustomerLastName", ReplyAction = "http://www.galasoft.ch/CustomerService/SaveCustomerLastNameResponse")]
        bool SaveCustomerLastName(string accountNumber, string newName);
    }
}
