/*
 * API
 *
 * Some API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ArrayOfCustomer struct {

	Customer []Customer `json:"customer,omitempty"`
}
