//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Customers
{
    public interface ICustomerService
    {
        ArrayOfCustomer GetCustomers(string lastName);

        Customer GetCustomerByAccountNumber(int accountNumber);

        ArrayOfCustomer GetAllCustomers();

        bool SaveCustomer(Customer editedCustomer);

        bool SaveCustomerLastName(string accountNumber, string newName);
    }
}
