//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invoke.CustomerServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/Customers")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressStreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Invoke.CustomerServiceReference.CustomerGender GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Uri PictureUriField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((this.AccountNumberField.Equals(value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressCity {
            get {
                return this.AddressCityField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressCityField, value) != true)) {
                    this.AddressCityField = value;
                    this.RaisePropertyChanged("AddressCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressCountry {
            get {
                return this.AddressCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressCountryField, value) != true)) {
                    this.AddressCountryField = value;
                    this.RaisePropertyChanged("AddressCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressStreet {
            get {
                return this.AddressStreetField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressStreetField, value) != true)) {
                    this.AddressStreetField = value;
                    this.RaisePropertyChanged("AddressStreet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Invoke.CustomerServiceReference.CustomerGender Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Uri PictureUri {
            get {
                return this.PictureUriField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureUriField, value) != true)) {
                    this.PictureUriField = value;
                    this.RaisePropertyChanged("PictureUri");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerGender", Namespace="http://schemas.datacontract.org/2004/07/Customers")]
    public enum CustomerGender : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Boy = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Girl = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.galasoft.ch", ConfigurationName="CustomerServiceReference.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.galasoft.ch/CustomerService/GetCustomers", ReplyAction="http://www.galasoft.ch/CustomerService/GetCustomersResponse")]
        Invoke.CustomerServiceReference.Customer[] GetCustomers(string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.galasoft.ch/CustomerService/GetCustomers", ReplyAction="http://www.galasoft.ch/CustomerService/GetCustomersResponse")]
        System.Threading.Tasks.Task<Invoke.CustomerServiceReference.Customer[]> GetCustomersAsync(string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.galasoft.ch/CustomerService/GetCustomerByAccountNumber", ReplyAction="http://www.galasoft.ch/CustomerService/GetCustomerByAccountNumberResponse")]
        Invoke.CustomerServiceReference.Customer GetCustomerByAccountNumber(int accountNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.galasoft.ch/CustomerService/GetCustomerByAccountNumber", ReplyAction="http://www.galasoft.ch/CustomerService/GetCustomerByAccountNumberResponse")]
        System.Threading.Tasks.Task<Invoke.CustomerServiceReference.Customer> GetCustomerByAccountNumberAsync(int accountNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.galasoft.ch/CustomerService/GetAllCustomers", ReplyAction="http://www.galasoft.ch/CustomerService/GetAllCustomersResponse")]
        Invoke.CustomerServiceReference.Customer[] GetAllCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.galasoft.ch/CustomerService/GetAllCustomers", ReplyAction="http://www.galasoft.ch/CustomerService/GetAllCustomersResponse")]
        System.Threading.Tasks.Task<Invoke.CustomerServiceReference.Customer[]> GetAllCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.galasoft.ch/CustomerService/SaveCustomer", ReplyAction="http://www.galasoft.ch/CustomerService/SaveCustomerResponse")]
        bool SaveCustomer(Invoke.CustomerServiceReference.Customer editedCustomer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.galasoft.ch/CustomerService/SaveCustomer", ReplyAction="http://www.galasoft.ch/CustomerService/SaveCustomerResponse")]
        System.Threading.Tasks.Task<bool> SaveCustomerAsync(Invoke.CustomerServiceReference.Customer editedCustomer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.galasoft.ch/CustomerService/SaveCustomerLastName", ReplyAction="http://www.galasoft.ch/CustomerService/SaveCustomerLastNameResponse")]
        bool SaveCustomerLastName(string accountNumber, string newName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.galasoft.ch/CustomerService/SaveCustomerLastName", ReplyAction="http://www.galasoft.ch/CustomerService/SaveCustomerLastNameResponse")]
        System.Threading.Tasks.Task<bool> SaveCustomerLastNameAsync(string accountNumber, string newName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : Invoke.CustomerServiceReference.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<Invoke.CustomerServiceReference.ICustomerService>, Invoke.CustomerServiceReference.ICustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Invoke.CustomerServiceReference.Customer[] GetCustomers(string lastName) {
            return base.Channel.GetCustomers(lastName);
        }
        
        public System.Threading.Tasks.Task<Invoke.CustomerServiceReference.Customer[]> GetCustomersAsync(string lastName) {
            return base.Channel.GetCustomersAsync(lastName);
        }
        
        public Invoke.CustomerServiceReference.Customer GetCustomerByAccountNumber(int accountNumber) {
            return base.Channel.GetCustomerByAccountNumber(accountNumber);
        }
        
        public System.Threading.Tasks.Task<Invoke.CustomerServiceReference.Customer> GetCustomerByAccountNumberAsync(int accountNumber) {
            return base.Channel.GetCustomerByAccountNumberAsync(accountNumber);
        }
        
        public Invoke.CustomerServiceReference.Customer[] GetAllCustomers() {
            return base.Channel.GetAllCustomers();
        }
        
        public System.Threading.Tasks.Task<Invoke.CustomerServiceReference.Customer[]> GetAllCustomersAsync() {
            return base.Channel.GetAllCustomersAsync();
        }
        
        public bool SaveCustomer(Invoke.CustomerServiceReference.Customer editedCustomer) {
            return base.Channel.SaveCustomer(editedCustomer);
        }
        
        public System.Threading.Tasks.Task<bool> SaveCustomerAsync(Invoke.CustomerServiceReference.Customer editedCustomer) {
            return base.Channel.SaveCustomerAsync(editedCustomer);
        }
        
        public bool SaveCustomerLastName(string accountNumber, string newName) {
            return base.Channel.SaveCustomerLastName(accountNumber, newName);
        }
        
        public System.Threading.Tasks.Task<bool> SaveCustomerLastNameAsync(string accountNumber, string newName) {
            return base.Channel.SaveCustomerLastNameAsync(accountNumber, newName);
        }
    }
}
